---
-
    name: meter_pipeline
    interval: 30
    meters:
        - "*"
    resources:
    transformers:
    publishers:
        - graphite://10.10.10.10:2003
-
    name: cpu_pipeline
    interval: 30
    meters:
        - "cpu"
    transformers:
        - name: "rate_of_change"
          parameters:
              target:
                  name: "cpu_util"
                  unit: "%"
                  type: "gauge"
                  scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
    publishers:
        - graphite://10.10.10.10:2003
-
    name: disk_pipeline
    interval: 30
    meters:
        - "disk.read.bytes"
        - "disk.read.requests"
        - "disk.write.bytes"
        - "disk.write.requests"
    transformers:
        - name: "rate_of_change"
          parameters:
              source:
                  map_from:
                      name: "disk\\.(read|write)\\.(bytes|requests)"
                      unit: "(B|request)"
              target:
                  map_to:
                      name: "disk.\\1.\\2.rate"
                      unit: "\\1/s"
                  type: "gauge"
    publishers:
        - graphite://10.10.10.10:2003
-
    name: network_pipeline
    interval: 30
    meters:
        - "network.incoming.bytes"
        - "network.incoming.packets"
        - "network.outgoing.bytes"
        - "network.outgoing.packets"
    transformers:
        - name: "rate_of_change"
          parameters:
              source:
                  map_from:
                      name: "network\\.(incoming|outgoing)\\.(bytes|packets)"
                      unit: "(B|packet)"
              target:
                  map_to:
                      name: "network.\\1.\\2.rate"
                      unit: "\\1/s"
                  type: "gauge"
    publishers:
        - graphite://10.10.10.10:2003

